# Generated by Django 2.0.5 on 2018-05-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
