# Generated by Django 2.1.2 on 2018-11-09 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=30)),
                ('game_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('correct_answer', models.CharField(default='no answers', max_length=200)),
                ('game_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizmeapp.Game')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizmeapp.Question'),
        ),
    ]
