# Generated by Django 2.1.2 on 2018-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='no answers', max_length=200),
        ),
    ]
