# Generated by Django 2.1.2 on 2018-11-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmeapp', '0003_remove_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.CharField(default='users.CustomUser', max_length=30),
        ),
    ]
